### PR TITLE
Rewrote landing page, cleaner, smaller and SEO friendly

### PR DESCRIPTION
**Pull request by Fsig**
The example URL has been sent to ingsoc on the forums.

### CODE REVIEW

**Comment by jolan** [comment]
Thank you very much for this, the old site was assembled from various wordpress plugins/themes to facilitate easy collaborative editing and then exported to a static site so the markup was a bit of a mess.

I like this a lot, it is indeed a major improvement.

I'm fine with stripping the stats from the top (I'm sure it's slow on mobile anyway) but we do want to demonstrate that the project is alive and active.  I guess adding a link to https://stats.decred.org/ (and round it out with https://wiki.decred.org, and https://mainnet.decred.org) would suffice.   Also maybe sprinkling some badges like https://img.shields.io/github/downloads/decred/decred-release/total.svg would be good.

Please let me know if you have any thoughts on that and if you want to work on it or not.  If not, I can take it from here.

**Comment by Fsig** [comment]
Thanks jolan, I have added links to the Wiki and Stats. The total badge slows down the page a fair bit, it might be worth making a PHP script or such to get a copy of the image every so often and save it to local storage to keep page speeds nice or cache the download count to a text file and make our own badge.

As I'm not up to date with the progress on the stats.decred.org website I assume it's a known issue that the node list is not complete?

**Comment by jcvernaleo** [comment]
Curious what the status of this PR is.  Is there something we are waiting on?  Or is there something on our end that we need to do or answer?  Or is this good enough and we should open issues for the remaining bits?

@Fsig the incomplete node list on stats.decred is a known thing.

**Comment by jolan** [comment]
I'll be merging it in the next day or two.

I'm working on some improvements that will stack on top of this PR.

**Pull request merged**
