### PR TITLE
disable blockcount temporarily

### PR DESCRIPTION
**Pull request by jolan**
Requested by @dajohi.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
This looks fine and would be OK by me.  Anything keeping it from going in?  @dajohi ?

**Comment by dajohi** [comment]
I am going to test again without this change with the latest dcrd changes.

**Comment by jcvernaleo** [comment]
@dajohi did you ever test this with the latest dcrd?  I'd love to either get this in or close it.

**Comment by jolan** [comment]
I'm just going to close this since I will be adding a cache so we can display the block height without the API being slammed.

**Pull request closed without merging**
